source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PXDToolkit_Example', :exclusive => true do
  pod "PXDToolkit", :path => "../"
end

target 'PXDToolkit_Tests', :exclusive => true do
  pod "PXDToolkit", :path => "../"
end
